name: Build and deploy to web hosting (cPanel)

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Build and Deploy the client.
    runs-on: ubuntu-latest
    env:
      WEB_ROOT: ${{ vars.HOSTING_WEB_ROOT }}
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$HOSTING_SSH_KEY" > ~/.ssh/hosting.key
          chmod 600 ~/.ssh/hosting.key
          cat >>~/.ssh/config <<END
          Host hosting
            HostName $HOSTING_SSH_HOST
            Port $HOSTING_SSH_HOST_PORT
            User $HOSTING_SSH_USER
            IdentityFile ~/.ssh/hosting.key
            StrictHostKeyChecking no
          END
        env:
          HOSTING_SSH_HOST: ${{ vars.HOSTING_SSH_HOST }}
          HOSTING_SSH_HOST_PORT: ${{ vars.HOSTING_SSH_HOST_PORT }}
          HOSTING_SSH_USER: ${{ vars.HOSTING_SSH_USER }}
          HOSTING_SSH_KEY: ${{ secrets.HOSTING_SSH_KEY }}

      - name: Copy distribution
        run: scp -r dist/ "hosting:$WEB_ROOT"
